MultipleFormSave/Controllers/SaveRowController.cs
using MultipleFormSave.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace MultipleFormSave.Controllers
{
    public class SaveRowController : Controller
    {
        private string connectionString = WebConfigurationManager.ConnectionStrings["SContext"].ConnectionString;
        // GET: SaveRow
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaveTableRow()
        {
            ViewBag.customerId = "Entry Product Name";
            return View();
        }
        public ActionResult SaveOrder(string name, String address, Order[] order)
        {
            //string result = "Error! Order Is Not Complete!";
            //if (name != null && address != null && order != null)
            //{

            SqlConnection connection = new SqlConnection(connectionString);
            string query = "INSERT INTO Customers(CustomerName, CustomerAddress) Values('" + name + "','" + address + "')";
            SqlCommand command = new SqlCommand(query, connection);

            connection.Open();

            command.ExecuteNonQuery();

            

            //string query1 = "SELECT MAX(CustomerId) FROM Customers ";
            string CustomerPK = "Select Ident_current('Customers')";  // Get data insert session primary key.
            SqlCommand command1 = new SqlCommand(CustomerPK, connection);
            int Id = Convert.ToInt32(command1.ExecuteScalar());   //Return the first column of the first row in the result set by the query.
            

            connection.Close();
            

            foreach (var item in order)
            {

                string query2 = "INSERT INTO [Order](ProductName, Quantity ,Price,Amount,CustomerId) Values('" + item.ProductName + "','" + item.Quantity + "','" + item.Price + "','" + item.Amount + "','" + Id + "')";
                SqlCommand command2 = new SqlCommand(query2, connection);
                connection.Open();
                command2.ExecuteNonQuery();
                connection.Close();

            }

            string result = "Success! Order Is Complete!";
            //}
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

MultipleFormSave/Views/SaveRow/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


<table class="table table-bordered">
    <thead>
        <tr>
            <th style="text-align:center">নম্বর</th>
            <th style="text-align:center">আর্মস/সার্ভিস</th>
            <th style="text-align:center">পদবী</th>
            <th style="text-align:center">নাম</th>
            <th style="text-align:center">শিক্ষার্থীর সাথে সম্পর্ক</th>
            <th style="text-align:center">ইউনিট/কর্মস্থল</th>
            <th style="text-align:center">কর্মরত/অবঃ</th>
            <th style="text-align:center">মন্তব্য</th>
            <th style="text-align:center">যোগ/বিয়োগ</th>
        </tr>
    </thead>

    <tbody class="relativesv-fields">
        <tr class="relativesv">
            <td>
                <input id="personal_no_0" type="text" class="form-control" name="rel_personal_no[]" value="">

                <input type="hidden" name="rel_occupations[]">
                <input type="hidden" name="rel_contact_no[]">
                <input type="hidden" name="rel_address[]">
            </td>
            <td>
                <input id="mf_id_0" type="text" class="form-control" name="rel_mf_ids[]" value="">


            </td>
            <td>
                <input id="rank_id_0" type="text" class="form-control" name="rel_rank_ids[]" value="">


            </td>
            <td>
                <input id="name_0" type="text" class="form-control" name="rel_names[]" value="">


            </td>
            <td>
                <input id="relation_0" type="text" class="form-control" name="relations[]" value="">

            </td>
            <td>
                <input id="unit_0" type="text" class="form-control" name="rel_units[]" value="">


            </td>
            <td>
                <select id="in_working_0" type="text" class="form-control" name="in_working[]">
                    <option value="1">হ্যাঁ</option>
                    <option value="0">না</option>
                </select>

            </td>
            <td>
                <input id="remarks_0" type="text" class="form-control" name="rel_remarks[]" value="">

                <input type="hidden" name="type[]" value="1">
            </td>
            <td>
                <a class="btn btn-outline-primary btn-add-relativesv" href="javascript:void(0)">
                    <span class="glyphicon glyphicon-plus"></span>
                </a>
            </td>
        </tr>
    </tbody>
</table>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>

    $(document).on('click', '.btn-add-relativesv', function (e) {
        e.preventDefault();
        var preschoolFields = $('.relativesv-fields'),
            currentEntry = $(this).parents('.relativesv:first'),
            newEntry = $(currentEntry.clone()).appendTo(preschoolFields);

        newEntry.find('input').val('');
        preschoolFields.find('.relativesv:not(:last) .btn-add-relativesv')
            .removeClass('btn-add-relativesv').addClass('btn-remove-relativesv')
            // .removeClass('btn-success').addClass('btn-danger')
            .html('<i class="fa fa-minus"></i>');
    }).on('click', '.btn-remove-relativesv', function (e) {
        $(this).parents('.relativesv:first').remove();

        e.preventDefault();
        return false;
    });
</script>

MultipleFormSave/Views/SaveRow/SaveTableRow.cshtml
@{
    ViewBag.Title = "SaveTableRow";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SaveTableRow</h2>


@using (Html.BeginForm("SaveTableRow", "SaveRow", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />

        <div class="form-group">
            @Html.Label("Customer Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" id="name" name="name" placeholder="Enter Customer Name" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Customer Address", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" id="address" name="address" placeholder="Enter Customer Address" class="form-control" />
            </div>
        </div>

        <div class="body-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-12">
                        <div class="panel">
                            <div class="panel-body">
                                <table class="table table-bordered table-hover small-text" id="tb">
                                    <thead>
                                        <tr class="tr-header">
                                            <th>Product Name</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Amount</th>
                                            <th>
                                                Action
                                                @*<a href="javascript:void(0);" style="font-size:18px;" id="addMore" title="Add More Order">
                                                    <span class="glyphicon glyphicon-plus"></span>
                                                </a>*@
                                            </th>
                                            
                                        </tr>
                                    </thead>
                                    
                                      
                                    <tbody class="relativesv-fields">
                                        <tr class="relativesv">

                                            <td><input type="text" id="productName" name="productName" placeholder="@ViewBag.customerId" class="form-control" /> </td>
                                            <td><input type="text" id="price" name="price" placeholder="Product Price" class="form-control cal-item" /> </td>
                                            <td><input type="text" id="quantity" name="quantity" placeholder="Quantity" class="form-control cal-item" /></td>
                                            <td><input type="text" id="amount" name="amount" placeholder="Amount" class="form-control" /></td>
                                            <td>
                                                <a class="btn btn-outline-primary btn-add-relativesv" style="float:left" href="javascript:void(0)">
                                                    <i class="fa fa-plus"></i>
                                                </a>
                                                @*<a href="javascript:void(0);"  class="btn btn-outline-primary btn-addBlank" style="float:right" title="Add More Order">
                                                    <i class="fa fa-clone"></i>
                                                </a>*@
                                            </td>
                                            

                                        </tr>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="3" class="text-right"><strong>Total:</strong></td>
                                            <td colspan="3" id="totalAmount"></td>
                                        </tr>
                                    </tfoot>
                                </table>
                               
                            </div>
                        </div>



                    </div>
                </div>
            </div>

        </div>



        <div class="form-group">
            <div class="">
                <button id="saveOrder" type="submit" class="btn btn-danger" style="float:left; margin:0px 60px;">Save Order</button>
                @*<input type="submit" value="Save Order" class="btn btn-success btn-block" style="float:left; margin:0px 60px;" />*@
            </div>
        </div>


    </div>
}


<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>

    
    $(document).on('input', '.cal-item', function () {
 
        var currentRow = $(this).parents('tr:first')
        var price = $(currentRow.find('input[name=price]')[0]).val()
        var qty = $(currentRow.find('input[name=quantity]')[0]).val()

        if (isNaN(parseFloat(price))) {
            rowAmount = 0 * parseFloat(qty);
        } else if (isNaN(parseFloat(qty))) {
            rowAmount = parseFloat(price) * 0;
        } else {
            rowAmount = parseFloat(price) * parseFloat(qty);
        }
        $(currentRow.find('input[name=amount]').eq(0)).val(rowAmount);

        TotalAmount();
   
    });
    

    //$(document).on('click', '.btn-addBlank', function (e) {
    //    var preschoolFields = $('.relativesv-fields'),
    //        currentEntry = $(this).parents('.relativesv:first'),
    //        newEntry = $(currentEntry.clone()).appendTo(preschoolFields);

    //    newEntry.find('input').val('');
    //    preschoolFields.find('.relativesv:not(:last) .btn-addBlank').removeClass('btn-addBlank').addClass('btn-remove-relativesv')

    //     //.removeClass('btn-success').addClass('btn-danger')

    //    .html('<i class="fa fa-minus"></i>');

    //}).on('click', '.btn-remove-relativesv', function (e) {
    //    $(this).parents('.relativesv:first').remove();
                       
    //    //TotalAmount();
        
    //    e.preventDefault();
    //    return false;
    //});

    $(document).on('click', '.btn-add-relativesv', function (e) {
        e.preventDefault();
        var preschoolFields = $('.relativesv-fields'),
            currentEntry = $(this).parents('.relativesv:first'),
            newEntry = $(currentEntry.clone()).appendTo(preschoolFields);

        newEntry.find('input').val();
        preschoolFields.find('.relativesv:not(:last) .btn-add-relativesv')
            .removeClass('btn-add-relativesv').addClass('btn-remove-relativesv')
            //  .removeClass('btn-success').addClass('btn-danger')
            .html('<i class="fa fa-minus"></i>');

        TotalAmount();

    }).on('click', '.btn-remove-relativesv', function (e) {
        $(this).parents('.relativesv:first').remove();

        TotalAmount();

        e.preventDefault();
        return false;
    });

    function TotalAmount() {
        var totalAmount = 0;
        $.each($("#tb tbody tr"), function () {
            totalAmount += parseFloat($(this).find('td:eq(3) input').val());
        });
        $("#totalAmount").text(totalAmount);
    }

    //$(function () {
    //    $('#addMore').on('click', function () {
    //        var data = $("#tb tr:eq(1)").clone(true).appendTo("#tb");
    //        data.find("input").val('');
    //    });
    //    $('#addWithValue').on('click', function () {
            
    //        var data = $("#tb tr:last").clone(true).appendTo("#tb");
    //        data.find("input").val();
    //    });
    //    $(document).on('click', '.remove', function () {
    //        var trIndex = $(this).closest("tr").index();
    //        if (trIndex > 0) {
    //            $(this).closest("tr").remove();
    //        } else {
    //            alert("Sorry!! Can't remove first row!");
    //        }
    //    });
    //});


    //After Click Save Button Pass All Data View To Controller For Save Database
    function saveOrder(data) {
        return $.ajax({
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            type: 'POST',
            url: "/SaveRow/SaveOrder",
            data: data,
            success: function (result) {
                alert(result);
                location.reload();
            },
            error: function () {
                alert("Error!")
            }
        });
    }

    //Collect Multiple Order List For Pass To Controller
    $("#saveOrder").click(function (e) {
        e.preventDefault();

        var orderArr = [];
        orderArr.length = 0;

        $.each($("#tb tbody tr"), function () {
            orderArr.push({
                productName: $(this).find('td:eq(0) input').val(),
                price: parseFloat($(this).find('td:eq(1) input').val()),
                quantity: parseInt($(this).find('td:eq(2) input').val()),
                amount: parseFloat($(this).find('td:eq(3) input').val())
            });
        });



        var data = JSON.stringify({
            name: $("#name").val(),
            address: $("#address").val(),
            order: orderArr
        });

        $.when(saveOrder(data)).then(function (response) {
            console.log(response);
        }).fail(function (err) {
            console.log(err);
        });
    });
</script>