MultipleFormSave/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MultipleFormSave.Models
{
    public class Teacher
    {
        public Teacher(int teacherId, string teacherName, string teacherEmail, string teacherAddress)
        {
            TeacherId = teacherId;
            TeacherName = teacherName;
            TeacherEmail = teacherEmail;
            TeacherAddress = teacherAddress;
        }

        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public string TeacherEmail { get; set; }
        public string TeacherAddress { get; set; }
    }
}

MultipleFormSave/Controllers/FormController.cs
using MultipleFormSave.BLL;
using MultipleFormSave.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace MultipleFormSave.Controllers
{
    public class FormController : Controller
    {
       
        private string connectionString = WebConfigurationManager.ConnectionStrings["SContext"].ConnectionString;
        [HttpPost]
        public ActionResult Save(FormCollection collection)
        {

            ArrayList RowList = new ArrayList();
            ArrayList objectArray =new ArrayList();
            
            for(int n = 0; n< 3; n++)
            {
                for(int a =0; a< 2; a++)
                {
                    var N = collection["name[" + n + "][" + a + "]"];
                    var ag = collection["age[" + n + "][" + a + "]"];
                    var desig = collection["Designation[" + n + "][" + a + "]"];
                    RowList.Add(N);
                    RowList.Add(ag);
                    RowList.Add(desig);
                }

                ArrayList RowList1 = new ArrayList();
                RowList1 = (ArrayList)RowList.Clone();
                objectArray.Add(RowList1);
                RowList.Clear();
            }

            foreach (ArrayList item in objectArray)
            {
                foreach (var k in item)
                {
                    var v = k;
                }
            }
           


            var formId = Convert.ToInt32(collection["form_id"]);
            SqlConnection connection = new SqlConnection(connectionString);
            string query = "SELECT * FROM FormInfo WHERE FormId = '" + formId + "' ";
            SqlCommand command = new SqlCommand(query, connection);

            connection.Open();
            
            SqlDataReader reader = command.ExecuteReader();
            var formList = new List<string>();
            
            while (reader.Read())
            {

                string FormElement = reader["FormElement"].ToString();
                formList.Add(FormElement);

            }
            reader.Close();
            connection.Close();

            StringBuilder sb = new StringBuilder(string.Empty);
            int countList = formList.Count();
            int i = 0;
            foreach (var item in formList)
            {
                sb.Append("@");
                sb.Append(item);
                if(i<countList)
                {
                    sb.Append(",");
                }
                i++;
            }
           
            string tableName = collection["table_name"];

            string query1 = "INSERT INTO "+tableName+" VALUES("+sb+")";
            SqlCommand command1 = new SqlCommand(query1, connection);
            StringBuilder sb1 = new StringBuilder();
       
            foreach (var item in formList)
            {
                sb1.Append("@");
                sb1.Append(item);
                command1.Parameters.AddWithValue(sb1.ToString(), collection[item] );
                sb1.Clear();
            }
            connection.Open();
            int rowEffect = command1.ExecuteNonQuery();
            connection.Close();

            string InController = tableName;
            if (rowEffect>0)
            {
                return RedirectToAction("Index", InController);
            }

            return View("Create", InController);
        }
    }
}

MultipleFormSave/Controllers/TeacherController.cs
using MultipleFormSave.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace MultipleFormSave.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        private string connectionString = WebConfigurationManager.ConnectionStrings["SContext"].ConnectionString;
        public ActionResult Index()
        {

            SqlConnection connection = new SqlConnection(connectionString);
            string query = "SELECT * FROM Teacher";
            SqlCommand command = new SqlCommand(query, connection);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            var teacherList = new List<Teacher>();
           
            while (reader.Read())
            {
                int    TeacherId = Convert.ToInt32(reader["TeacherId"]);
                string TeacherName = reader["TeacherName"].ToString();
                string TeacherEmail = reader["TeacherEmail"].ToString();
                string TeacherAddress = reader["TeacherAddress"].ToString();
                Teacher teacher = new Teacher(TeacherId, TeacherName, TeacherEmail, TeacherAddress);
                teacherList.Add(teacher);
            }
            reader.Close();
            connection.Close();
            return View(teacherList);
        }
        public ActionResult Create()
        {
            return View();

        }
    }
}

MultipleFormSave/Views/Teacher/Create.cshtml
@model MultipleFormSave.Models.Teacher

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@*@Html.BeginForm(“detail”,”EmployeeController”, FormMethod.Post)*@
@using (Html.BeginForm("Save", "Form", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Teacher</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input id="form_id" name="form_id" type="hidden" value="2" />
        <input id="table_name" name="table_name" type="hidden" value="Teacher" />
        <div class="form-group">
            @Html.LabelFor(model => model.TeacherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <table class="table table-bordered table-hover" style="padding:0px">

            <tr class="bg-primary">
                <th>Name</th>
                <th>Age</th>
                <th>Designation</th>
            </tr>

            @for (int i = 0; i < 3; i++)
            {
               

                <tr>
                    <td><input name="name[@i]" type="text" class="form-control" style="padding:0px"/></td>
                    <td><input name="age[@i]" type="text" class="form-control" style="padding:0px"/></td>
                    <td><input name="Designation[@i]" type="text" class="form-control" style="padding:0px" /></td>
                </tr>
               
                <tr>
                    <td colspan="100">
                        <table class="table table-bordered">
                            <tr class="bg-success">
                                <th>Name</th>
                                <th>Age</th>
                                <th>Designation</th>
                            </tr>
                            @for (int j = 0; j < 3; j++)
                            {
                                        
                                <tr>
                                    <td><input name="name[@i][@j]" type="text" class="form-control" style="padding:0px" /></td>
                                    <td><input name="age[@i][@j]" type="text" class="form-control" style="padding:0px" /></td>
                                    <td><input name="Designation[@i][@j]" type="text" class="form-control" style="padding:0px" /></td>
                                </tr>
                                        
                            }
                        </table>
                    </td>
                </tr>

            }
        </table>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MultipleFormSave/Views/Teacher/Index.cshtml
@model IEnumerable<MultipleFormSave.Models.Teacher>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeacherName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeacherEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeacherAddress)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(mi => item.TeacherName)
        </td>
        <td>
            @Html.DisplayFor(mi => item.TeacherEmail)
        </td>
        <td>
            @Html.DisplayFor(mi => item.TeacherAddress)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TeacherId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TeacherId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TeacherId })
        </td>
    </tr>
}

</table>